apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: springboot
  namespace: spring-liberty
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/spring-liberty/springboot:0.0.1-SNAPSHOT
  pullPolicy: Always
  serviceAccountName: spring-liberty
#  createKnativeService: true
  manageTLS: false
  expose: true
  service:
    type: ClusterIP
    port: 9080
