apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: springboot
  namespace: spring-liberty
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSoruce: Standalone
  applicationImage: image-registry.openshift-image-registry.svc:5000/spring-liberty/springboot:0.0.1-SNAPSHOT
  pullPolicy: Always
  serviceAccountName: spring-liberty
#  createKnativeService: true
  manageTLS: false
  expose: true
  service:
    type: ClusterIP
    port: 9080
